### PR TITLE
Adds validation of latex template in github actions and in docker

### PR DESCRIPTION
**Pull request by matsavage**
Some changes to make sure all of the code works as expected (can you tell I am working on a lot of validation projects at the moment)

Changes:
* Runs 4 modes of running dungeonsheets post unit testing, to make sure outputted LaTeX documents compile, ePub exports etc
* Updates Dockerfile with luatex
* Run same 4 modes of running dungeonsheets on built Dockerfile to make sure all functions work with Docker

### CODE REVIEW

**Comment by PJBrs** [comment]
l pulled your changes into my wip branch... Apparently github is not sufficiently savvy to check what gets merged where (-:

**Comment by PJBrs** [comment]
OK, so I merged this one locally, then squashed it, then merged it here to show it's merged, then I force pushed my local changes back again, hahaha!

**Comment by PJBrs** [comment]
I still don't understand how to run this locally though. So if I run docker, I can go `docker run -it -v $(pwd):/build ghcr.io/canismarko/dungeon-sheets:latest` and then it will run the branch that I have checked out?

**Comment by PJBrs** [comment]
... I get sth like Error response from daemon: manifest unknown...

**Comment by matsavage** [comment]
thanks for accepting the changes. 

so running the command you posted will use the pre-built docker image from Mark’s repo with the tag ‘latest’

that currently doesn’t exist as the person who made it originally had it so when the package is pushed it has the tag ‘’master’ i changed this in the pipeline and the docs as ‘latest’ is standard. 

you can try the same command but with my repo in the path name or you can build a new image locally with 

docker build . -t=something

then substitute the image name in the above command for something 

sorry on my phone or i could give more details

**Comment by PJBrs** [comment]
I also noticed that the docker test fails online....

And I still do not understand how to work docker locally. The only thing that worked for me was:
```
docker build . --tag=ds
cd examples
docker run -it -v $(pwd):/../build ds
```

**Comment by PJBrs** [comment]
Hiya!

So, I'm a bit lost... I can only pass tags that are in the canismarko repo itself? I'd like to be able to tell people how to test my branch with the docker image...

... and I don't understand why the test doesn't pass. Locally, most of it passes (some examples take too long on my very ancient thinkpad-t420s with kubuntu 20.04), so I know it works.

... and who can change that tag to "latest"?

**Comment by matsavage** [comment]
The tests all pass on your branch but pushing to the github artifact repository isn’t working, 

You’ll need to set this up for your account and link it to the repo etc. I managed to do it last weekend but it was a bit of an involved process and the error messages weren’t too helpful

**Comment by matsavage** [comment]
https://github.com/matsavage/dungeon-sheets/pkgs/container/dungeon-sheets

the one on my repo should work for you

**Comment by matsavage** [comment]
actually looks like this is the issue, from the pipeline

Run docker tag  ghcr.io/pjbrs/dungeon-sheets:master ghcr.io/PJBrs/dungeon-sheets:latest
Error parsing reference: "ghcr.io/PJBrs/dungeon-sheets:latest" is not a valid repository/tag: invalid reference format: repository name must be lowercase

if you have a repository set up in the lowercase, then maybe something needs to be done to the pipeline to also push to the lowercase?

**Comment by matsavage** [comment]
i feel like this package should work. 

https://github.com/PJBrs/dungeon-sheets/pkgs/container/dungeon-sheets

all that last step just also adds the tag of latest

**Comment by matsavage** [comment]
but :master should be fine

**Comment by PJBrs** [comment]
OK, I'm too far out of my depth, unfortunately... I didn't know I (I?) had created that "package" (?) in my own repo. I did see that all tests complete fine here, which means that they should also complete over at canismarko's repo, at least when they're pulled into master... Right? 

...

And wrt. standards... My main git branch would normally be named "latest"? I did notice that some repos changed from master to main...?

**Comment by PJBrs** [comment]
https://github.com/orgs/community/discussions/25768 ?

https://github.com/docker/build-push-action/issues/37 ...

Oh... I've downloaded "my" package, but it builds the fillable forms... I think I need to pass --tex-template or sth?

=== EDIT ===

OK, I think I'm finally starting to get it... So, I can either download a pre-specified (prebuilt) docker container from  ghcr.io, or I can build one locally from an existing tree, provided that I have a dockerfile.  ....  And my tests here fail because that tag business should have used a lowercase version of env.IMAGE_NAME, which requires some additional work.

**Comment by PJBrs** [comment]
Apparently, the "magic" way to fix this is somewhere in here:
https://github.com/docker/build-push-action/issues/237#issuecomment-848673650

```
name: kontarion push

on:
  workflow_dispatch:
  push:
    paths:
      - '1.7.0/**'
      - '.github/workflows/push-kontarion.yml'

jobs:
  kontarion-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/kontarion
        tags: |
          type=raw,value=1.0.${{ github.run_number }},priority=1000
          type=ref,event=branch
          type=sha
          type=raw,value=latest
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: ./1.7.0
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
```

**Comment by PJBrs** [comment]
@matsavage  So, I succeeded in fixing the final docker deployment step :-)

But I really can't figure out what I'm doing wrong with the python workflow file. I'm basically following your steps, but somehow my workflow fails hard, while I only tried to be a little bit less redundant yet. Would you mind having a look [over here](https://github.com/PJBrs/dungeon-sheets/blob/master/.github/workflows/python_ci.yml)?

The difference with yours would seem negligible:

```
git diff remotes/msavage/master..HEAD .github/workflows/python_ci.yml
diff --git a/.github/workflows/python_ci.yml b/.github/workflows/python_ci.yml
index 663dda1..87c799f 100644
--- a/.github/workflows/python_ci.yml
+++ b/.github/workflows/python_ci.yml
@@ -13,13 +13,13 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest]
-        python-version: ['3.9', '3.10', '3.11', '3.12']
+        python-version: ['3.9', '3.10', '3.11']
 
     steps:
     - uses: actions/checkout@v4
       with:
         submodules: recursive
-  
+
     - name: Set up required system dependencies
       run: |
         sudo apt-get update
@@ -35,41 +35,50 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -e ".[dev]"
+
     - name: Run flake
       run: flake8 dungeonsheets/ --exit-zero
+
     - name: Run tests
       run: pytest --cov=dungeonsheets tests/
-  
+
   render_examples:
-    name: "Render all examples"
+    name: "Test python-3.12, render all examples"
     runs-on: ubuntu-latest
     needs: [build]
     strategy:
       matrix:
-        build-command: ["", "--fancy", "--tex-template", "--output-format=epub"]
+        build-command: ["", "--fancy --tex-template --spells-by-level --feats-by-type", "--output-format=epub"]
+
     steps:
     - uses: actions/checkout@v4
       name: Checkout Repo
       with:
         submodules: recursive
 
+    - name: Set up required system dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get -y install pdftk texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-luatex texlive-pstricks
+
     - name: Set up Python 3.12
       uses: actions/setup-python@v4
       with:
         python-version: 3.12
         cache: pip
 
-    - name: Set up required system dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get -y install pdftk texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-luatex texlive-pstricks
-
     - name: Install dependencies and do a local pip install
       run: |
         python -m pip install --upgrade pip
         pip install -e ".[dev]"
 
+    - name: Run flake
+      run: flake8 dungeonsheets/ --exit-zero
+
     - name: Render examples with ${{ matrix.build-command }}
       run: |
         cd examples
         makesheets --debug ${{ matrix.build-command }}
+
+    - name: Run tests
+      run: pytest --cov=dungeonsheets tests/
```

Weirdly, I configured the tests for the docker image the same way, and [they complete fine](https://github.com/PJBrs/dungeon-sheets/actions/runs/8712027071).

**Comment by matsavage** [comment]
I would suggest adding 3.12 back into the top workflow, I don't think the issue of installing the dependencies twice for 3.12 is that much of a problem, especially at the cost of modularity.

Where is this failing? In the PR: https://github.com/canismarko/dungeon-sheets/pull/147

This will be using the pipeline defined in the `master` of the repo it's in, and not the one in the PR, you can access the code for the workflow that was run from the "Workflow file" tab on the left side of the workflow run you want to look at.

**Comment by matsavage** [comment]
Looking at the outcome from the pipeline, the bloodhunter latex file was the issue, I had issues with this a couple of times when running the pipeline in my repo too, and it would work when I re-ran the pipeline, so there may be some transient issue with how this file is being generated

**Comment by PJBrs** [comment]
Nevermind, I found the stupid mistake.

To give us a little bit more leeway, I decided to load the `dndtemplate` before the `dnd` package. Now dnd needs to pass the `table` option to the `xcolors` package in order for `\rowcolors` to be defined. Apparently, this happens automatically on texlive-2022 (docker) and at my own computer (texlive-2023), but not in github (texlive-2021), so I needed to add `\PassOptionsToPackage{table}{xcolor}`

**Comment by matsavage** [comment]
Oh nice, what was it?

I feel like LaTeX changes so much between versions and installs, it’s really not easy

**Comment by PJBrs** [comment]
Tried to describe the problem above, hahaha!

The changes below needed that extra line of `\PassOptionsToPackage{table}{xcolor}`

```
diff --git a/dungeonsheets/forms/MSavage_template.tex b/dungeonsheets/forms/MSavage_template.tex
index 3b358ef..f74ac44 100644
--- a/dungeonsheets/forms/MSavage_template.tex
+++ b/dungeonsheets/forms/MSavage_template.tex
@@ -1,13 +1,14 @@
 \documentclass[letterpaper,openany,oneside,twocolumn]{book}
 
+\PassOptionsToPackage{table}{xcolor}
+
+\usepackage{bookmark}
 \usepackage{fontspec}
+\usepackage{dndtemplate}
 \usepackage[justified]{dnd}
 \usepackage{ifthen}
 \usepackage{pstricks}
 
-\usepackage{dndtemplate}
-\usepackage{bookmark}
-
 \setlength\oddsidemargin{\dimexpr(\paperwidth-\textwidth)/2 - 1in\relax}
 \setlength\evensidemargin{\oddsidemargin}

``` 

I wanted to load dndtemplate before dnd so that it is easier to make local changes. This is part of a patch that loads local dnd and dndtemplate packages if kpsewhich can find them, and only otherwise use the packages bundled with dungeonsheets.

**Comment by PJBrs** [comment]
[This patch.](https://github.com/PJBrs/dungeon-sheets/commit/3ed6fe0e46c5852acb273b0cb263a35f313c83f9)

**Comment by matsavage** [comment]
ahh sorry. I misunderstood

**Pull request merged**
